version: '3'

services:
  db:
    container_name: "Auth-Service_database"
    image: "postgres:11.3-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication
    volumes:
      - ./volumes/db/init/:/docker-entrypoint-initdb.d/ # init database
      - ./volumes/db/data/:/var/lib/mysql/              # data storage
    ports:
      - "9020:5432"     #Default
    restart: unless-stopped
