version: '3'

services:
  db:
    container_name: "Pricing-Service_database"
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./volumes/db/data/:/var/opt/mssql             # data storage
    ports:
      - "3300:3306"     #Default
    restart: unless-stopped
